# Generated by Django 5.2 on 2025-06-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0004_reuniao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tag',
            field=models.CharField(choices=[('G', 'Gestão'), ('M', 'Marketing'), ('RH', 'Gestão de pessoas'), ('I', 'Impostos'), ('DA', 'Dificuldade em Aprendizagem'), ('D', 'Dúvidas Gerais')], max_length=2),
        ),
    ]
